import TaskModel from '../models/task';
import moment from 'moment';

const data: TaskModel[] = [
  {
    id: '0',
    category: 'Sports',
    title: 'GYM',
    start: '10:00',
    end: '12:00',
    date: moment().toDate(),
    repeats: true,
    repeatingDays: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
    reminder: 15,
  },
  {
    id: '1',
    category: 'Study',
    title: 'ADM 2701',
    start: '13:00',
    end: '15:00',
    date: moment().toDate(),
    repeats: false,
    reminder: 30,
  },
  {
    id: '2',
    category: 'Leisure',
    title: 'Boyz night ',
    start: '15:00',
    end: '17:00',
    date: moment().toDate(),
    repeats: false,
    reminder: 30,
  },
  {
    id: '3',
    category: 'Other',
    title: '???????',
    start: '19:00',
    end: '21:00',
    date: moment().toDate(),
    repeats: false,
    reminder: 30,
  },
  {
    id: '4',
    category: 'Sports',
    title: 'GYM',
    start: '10:00',
    end: '12:00',
    date: moment().add('day', 5).toDate(),
    repeats: false,
    reminder: 60,
  },
  {
    id: '5',
    category: 'Study',
    title: 'ADM 2701',
    start: '13:00',
    end: '15:00',
    date: moment().add('day', 6).toDate(),
    repeats: false,
    reminder: 15,
  },
  {
    id: '6',
    category: 'Leisure',
    title: 'Boyz night',
    start: '15:00',
    end: '17:00',
    date: moment().add('day', 7).toDate(),
    repeats: false,
    reminder: 30,
  },
  {
    id: '7',
    category: 'Other',
    title: '???????',
    start: '19:00',
    end: '21:00',
    date: moment().add('day', 8).toDate(),
    repeats: false,
    reminder: 30,
  },
];

export default data;
